# Exercise template for Python basics

## Variables, data types, ...

Basic printing

In [0]:
print('Hello world')

## Inspecting objects

In [2]:
a = 5
type(a)

int

In [3]:
dir(a)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

In [4]:
help(a)

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __ceil__(...)
 |      Ceiling of an Integral retur

In [8]:
# use tab completion
a

5

## Print et al

In [9]:
a = 4
b = 5
print(a)
print(a,b)
print('A %d plus %d' % (a,b))
print(f'A {a} plus {b}')
print('A {} plus {}'.format(4,5))

4
4 5
A 4 plus 5
A 4 plus 5
A 4 plus 5


In [10]:
li = [1.23, 3.456, 5.67]
print('%.1f %.1f ' % (12.3445, 34))
print('%.1f ' % li)



12.3 34.0 


TypeError: must be real number, not list

What happened here? 

---


Basically, we need to give the number explicitly and cannot print a list like this, we have to be a bit smarter about it:

In [11]:
li = [1.23, 3.456, 5.67]

# printing the list using * operator separated  
# by space  
print(*li) 
  
# printing the list using * and sep operator 
print("printing lists separated by commas") 
  
print(*li, sep = ", ")  
  
# print in new line 
print("printing lists in new line") 
  
print(*li, sep = "\n") 

1.23 3.456 5.67
printing lists separated by commas
1.23, 3.456, 5.67
printing lists in new line
1.23
3.456
5.67


## Simple types

In [12]:
a = 3
b = 3+0.0
c = False
d = a==b
print(a,type(a))
print(b,type(b))
print(c,type(c))
print(d,type(d))

3 <class 'int'>
3.0 <class 'float'>
False <class 'bool'>
True <class 'bool'>


## Lists

In [13]:
a = []
b = [1, 2, 4]
c = [5, "Hello", "World"]
d = a==[]
print(a,type(a),len(a))
print(b,type(b),len(b))
print(c,type(c),len(c))
print(d,type(d))
len(d)

[] <class 'list'> 0
[1, 2, 4] <class 'list'> 3
[5, 'Hello', 'World'] <class 'list'> 3
True <class 'bool'>


TypeError: object of type 'bool' has no len()

What happened here?
Look at the error! object of type 'bool' has no len()
This means bool objects don't have a __len__ attribute.
Let's check this by "tabbing" our variable:


In [18]:
d.__bool__
b.__len__

<method-wrapper '__len__' of list object at 0x000001D9C2402388>

We could also check the help for the length function:

In [19]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



## Variable Assignment - Understanding Reference Semantics 

In [20]:
4
a=4
print(a)

4


In [21]:
a = [1,2,3]
b = a
a.append(4)
print(a)
print(b)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [22]:
c = a.copy()
a.append(5)
print(a)
print(c)
a.insert(2,6)
print(a)

[1, 2, 3, 4, 5]
[1, 2, 3, 4]
[1, 2, 6, 3, 4, 5]


In [0]:
help(a.insert)

## List vs String - Mutable vs Immutable

In [23]:
nus = [1,2,3,4,5,6,7,8]
print(nus[3])                   # indexing: 0 is first entry
nus[3] = 'Four'
print(nus)

4
[1, 2, 3, 'Four', 5, 6, 7, 8]


In [24]:
smiles = "C(=N)(N)N.C(=O)(O)O"
print(smiles[3])


N


In [25]:
smiles[3] = '4'

TypeError: 'str' object does not support item assignment

What happened here?
Look at the error! 'str' object does not support item assignment
This means we cannot chnage the third position in this string and exchange the letter N with the number 4.

In [26]:
i = 3
i = 4
print(i)
str = 'Hello'
str += ' World'
print(str)

4
Hello World


So:
- You can change the list entry (mutable), but not the string entry (immutable)
- You can't really change the integer/string (immutable), so Python instead makes a new integer/string

... it is now time for an exercise

## Exercise: 
Make variables containing your name, height, family members and their ages.
Consider choice of data types.
Display the variables and their types.
Change their values (mutable?).
Add a new family member.

In [0]:
# Assign two variables, e.g. myname and myheight, with your name and your height


What are natural data types for these? Names are naturally strings, while measurements are most often numbers. Multiple things can easily be established as lists.

In [0]:
# How do you inspect the data types that you created?


In [0]:
# Each family member should have name and age. What is a good container for a fixed number of variables?

# The container for you entire family shold be able to change size. What is suitable for that?

# How do you add a member to the family container?

# What happens when you run this cell multiple times?

## Numpy
We have by now seen different datatypes. One of the most commonly encountered datatype is the numerical array. 
Python has a specialised library with some powerful indexing and advanced methods called numPy. We delve into some basics here.

In [29]:
# Numpy is not a built-in package; it has to be loaded
import numpy as np 
# This is a standard way of importing packages
# And you can import a package using another identifier, 
# here numpy is being loaded as np. 

# Once you have numpy loaded, a tab after np. should show
# tons of powerful functions that are now at your finger tips

# Don't be shy! Read the docs. Invoke any intriguing function
# with its help(np.any_function_you_wish)
# Ex: help(np.random)

In [27]:
import numpy as np
m = np.random.randint(0,10,(3,4))

In [0]:
# A numerical list has to be cast explicitly as a numpy array

# Our good old numerical list
nus = [1,2,3,4,5,6,7,8]

# Check what is its type
print(type(nus))

# Now let us cast it as a numpy array
# Use dir or tab after nus to see what methods and functions are available
nus

In [0]:
# Create a 4x4 array of zeros
z = np.zeros([4, 4])
print(z)

# Create a 4x4 array of ones
o = np.ones([4,4])
print(o)

# Create a 4x4 diagonal matrix with 1 as diagonal entries
d = np.diag([1,1,1,1])
print(d)

In [0]:
# More numpy-ing

# Create a random integer matrix, with entries between 0-9,
# of size 4x4 
m = np.random.randint(10,size=(4, 4))

# Print the matrix
print(m)

# Print only the first column
print(m[:,0])

# Print the last row
print(m[-1,:])



In [0]:
# Make transpose of the matrix
print(m)
m.T
print(m)

What happened here? The matrix wasn't transposed? Let's look at this.

In [0]:
help(m.T)

In [0]:
# Compute the mean value
print(m.mean())

# Compute row-wise mean
print(m.mean(axis=0))

# Compute column-wise mean
print(m.mean(axis=1))

## Exercise:
Let's try and play around further with numpy. Use the help() function if you are in doubt.

In [39]:
# Create another matrix of dimensions 4x4
n = np.random.randint(10, size=(16)).reshape((4,4))
m = np.random.randint(10, size=(16)).reshape((4,4))

# Compute the element-wise product of the two matrices
hadamard = np.multiply(m, n)

# Compute the matrix product of the two matrices
prod = np.matmul(m, n)

print(hadamard)
print(prod)


[[ 8 56  2  9]
 [21 12  7  0]
 [ 0 30 48  8]
 [20  0  0 18]]
[[ 62  43  61  36]
 [ 40  42  42  36]
 [107 115  99 112]
 [ 81  83  91  70]]


In [50]:
# Create a new random matrix of size 1x12
a = np.random.randint(10, size=(12)).reshape((1,12))
print(a)

# Reshape it into a 2D array of size 3x4 
a = a.reshape((3,4))
print(a)

# Reshape it into a 3d array of size 2x2x3
a = a.reshape((2,2,3))
print(a)

[[1 4 4 2 8 8 9 0 4 8 7 2]]
[[1 4 4 2]
 [8 8 9 0]
 [4 8 7 2]]
[[[1 4 4]
  [2 8 8]]

 [[9 0 4]
  [8 7 2]]]
